//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Destination
{
	Destinations queue;		
	Transform thingMoving;
	public Vector3 coords;
	public float speed;
	public float pauseTime;
	Vector3 step;
	int steps;
	int i;
	public Destination (Transform thingMoving, Destinations queue, Vector3 coords, float speed, float pauseTime)
	{
		this.thingMoving = thingMoving;
		this.queue = queue;
		this.coords = coords;
		this.speed = speed;
		this.pauseTime = pauseTime;
	}
	public void Initialize()
	{
		Vector3 diff = coords - thingMoving.position;
		step = diff * Time.fixedDeltaTime;
		int steps = (int)(diff.magnitude/step.magnitude);
	}
	public void Move()
	{
		if(i < steps)
		{
			i++;
			thingMoving.position += step;
		}
		else
		{
			thingMoving.position = coords;
			queue.Next ();
		}
	}
}



