//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;
using System.Collections;
using System.Linq;

public class Discard:Placeholder
{
	public List<Card> Recycle()
	{
		var list = new List<Card>();
		foreach(var card in cards)
		{
			card.enabled = true;
			card.GetComponent<Renderer>().enabled = true;
			list.Add (card);
		}
		cards.Clear();
		return list;
	}	
	override public void Update()
	{
		base.Update ();
	}
	override public void Clicked(MouseEvent evt)
	{
	
	}
}


