//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class CustomMouse: MonoBehaviour
{
	protected bool _isHighlighted = false;
	public virtual bool isHighlighted { get; set;}
	public virtual void MouseOver(){}
	public virtual void Clicked(MouseEvent evt)
	{

	}
	public virtual void RecordUndo()
	{

	}
	public virtual void Highlight(Color color)
	{
		isHighlighted = true;
	}
	public virtual void UnHighlight()
	{
		isHighlighted = false;
	}
	public virtual void MouseExit()
	{
	}
}

