//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Sinwave
{
		float frequency;
		float baseValue;
		float currentAngle;
		float stepAngle;
		float currentValue;

		public Sinwave (float frequency, float baseValue)
		{
			this.frequency = frequency;
			this.baseValue = baseValue;
			stepAngle = (2*Mathf.PI) * (frequency * Time.fixedDeltaTime);
		}
		public float NextValue()
		{
			currentAngle += stepAngle;
			currentValue = Mathf.Sin (currentAngle)/2 + baseValue;
			return currentValue;			
		}
}


