//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace XBoxController
{
	public enum XBoxControlsEnum
	{
		A,B,X,Y,
		LB,RB,
		LeftThumbButton, RightThumbButton,
		Start,
		Select,
		D_PAD_LEFT, D_PAD_RIGHT, D_PAD_UP, D_PAD_DOWN,
		D_PAD_X, D_PAD_Y, 
		LeftThumb_X, LeftThumb_Y, 
		RightThumb_X, RightThumb_Y, 
		RT, LT
	}
	public enum MouseEnum
	{
		LeftClick,
		RightClick
	}

}

